backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master


  ### enable below lines for github integration ###npx netlify-cms-proxy-server
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

site_url: https://happy-colden-825498.netlify.app

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
  - label: "Pages"
    name: "Pages"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "src/index.json"
        fields:
          - { label: 'The field label', name: someVar, widget: string, hint: "Some instructions here" }

